# -*- coding: utf-8 -*-
"""
Created on Wed Apr  9 13:34:16 2025

@author: nerij
"""

# noise_and_plot_functions.py
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import splprep, splev

def add_noise_simple(arr, noise_level):
    """
    Add random Gaussian noise to an array using noise_level as sigma.
    """
    return arr + np.random.normal(0, noise_level, size=arr.shape)

def create_noisy_shape(row, shape_x_cols, shape_y_cols, noise_level=0.1):
    """
    Fit a periodic spline to the 9 shape points in the row,
    sample 100 equally spaced points along the spline, add noise (using noise_level)
    to these points, and then select 10 equidistant points (with the first and last identical)
    so that the shape is closed.
    
    Returns:
        x_noisy: A 1D NumPy array of 10 noisy x values.
        y_noisy: A 1D NumPy array of 10 noisy y values.
    """
    # Extract original 9 points.
    x = row[shape_x_cols].to_numpy(dtype=float)
    y = row[shape_y_cols].to_numpy(dtype=float)
    # Fit a periodic spline.
    tck, _ = splprep([x, y], s=0, per=True)
    u_new = np.linspace(0, 1, 100)
    x_spline, y_spline = splev(u_new, tck)
    # Add noise to the spline.
    x_noisy_full = x_spline + np.random.normal(0, noise_level, size=x_spline.shape)
    y_noisy_full = y_spline + np.random.normal(0, noise_level, size=y_spline.shape)
    # Select 10 equidistant indices (the first and last will be effectively the same).
    indices = np.linspace(0, 99, 10, endpoint=True).astype(int)
    return x_noisy_full[indices], y_noisy_full[indices]

def get_smooth_curve(x_points, y_points, num_points=200):
    """
    Given a set of sampled points (x_points, y_points),
    fit a periodic spline (assuming the input points define a closed curve)
    and evaluate a dense set of points along the spline.
    
    Returns:
        x_dense, y_dense: Dense NumPy arrays representing the smooth curve.
    """
    tck, _ = splprep([x_points, y_points], s=0, per=True)
    u_dense = np.linspace(0, 1, num_points)
    x_dense, y_dense = splev(u_dense, tck)
    return x_dense, y_dense

def compute_means_pair(data, cols_x, cols_y, groups=5):
    """
    Split the DataFrame into 'groups' nearly equal parts and compute the mean (column-wise)
    of the specified columns.
    
    Returns:
        mean_x: NumPy array of shape (groups, len(cols_x))
        mean_y: NumPy array of shape (groups, len(cols_y))
    """
    splits = np.array_split(data, groups)
    mean_x = [grp[cols_x].mean().to_numpy() for grp in splits]
    mean_y = [grp[cols_y].mean().to_numpy() for grp in splits]
    return np.array(mean_x), np.array(mean_y)

def plot_comparison(ax, normal_df, noisy_df, cols_x, cols_y, title):
    """
    Plot curves from normal and noisy data on the given axis.
    Labels are added only for the first normal and first noisy curve.
    """
    first_normal, first_noisy = True, True
    for _, row in normal_df.iterrows():
        x = row[cols_x].to_numpy(dtype=float)
        y = row[cols_y].to_numpy(dtype=float)
        if first_normal:
            ax.plot(x, y, marker='o', linestyle='-', color='blue', alpha=0.3, label='Normal')
            first_normal = False
        else:
            ax.plot(x, y, marker='o', linestyle='-', color='blue', alpha=0.3)
    for _, row in noisy_df.iterrows():
        x = row[cols_x].to_numpy(dtype=float)
        y = row[cols_y].to_numpy(dtype=float)
        if first_noisy:
            ax.plot(x, y, marker='s', linestyle='--', color='red', alpha=0.3, label='Noisy')
            first_noisy = False
        else:
            ax.plot(x, y, marker='s', linestyle='--', color='red', alpha=0.3)
    ax.set_title(title)
    ax.set_xlabel(cols_x[0].split('_')[0])
    ax.set_ylabel(cols_y[0].split('_')[0])
    ax.legend(loc='upper right')

def plot_means(ax, norm_mean_x, norm_mean_y, noisy_mean_x, noisy_mean_y, noisy_examples, cols_x, cols_y, title):
    """
    Plot the mean curves (normal and noisy) on the axis along with example noisy curves.
    The smooth curves are generated by connecting the 10 sample points with a periodic spline.
    Labels are added only once per type.
    """
    for i in range(norm_mean_x.shape[0]):
        # Generate smooth curve from normal mean sample points.
        x_dense, y_dense = get_smooth_curve(norm_mean_x[i], norm_mean_y[i], num_points=200)
        ax.plot(x_dense, y_dense, color='navy', linewidth=3,
                label='Normal Mean' if i==0 else "")
    for i in range(noisy_mean_x.shape[0]):
        x_dense, y_dense = get_smooth_curve(noisy_mean_x[i], noisy_mean_y[i], num_points=200)
        ax.plot(x_dense, y_dense, color='darkred', linestyle='--', linewidth=3,
                label='Noisy Mean' if i==0 else "")
    for idx, row in noisy_examples.iterrows():
        # Use the sampled 10 points to plot the example smooth curve.
        x_sample = row[cols_x].to_numpy(dtype=float)
        y_sample = row[cols_y].to_numpy(dtype=float)
        x_dense, y_dense = get_smooth_curve(x_sample, y_sample, num_points=200)
        ax.plot(x_dense, y_dense, marker='x', linestyle=':', color='orange', alpha=0.7,
                label='Noisy Example' if idx==0 else "")
    ax.set_title(title)
    ax.set_xlabel(cols_x[0].split('_')[0])
    ax.set_ylabel(cols_y[0].split('_')[0])
    ax.legend(loc='upper right')
